 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build --nologo

   test:
     executor: win/default

     steps:
        - run: nuget install NUnit.ConsoleRunner -Version 3.11.1 -OutputDirectory .\tools
        - run: .\tools\NUnit.ConsoleRunner.3.11.1\tools\nunit3-console.exe .\src\Arbiter.Tests\bin\Debug\net48\Arbiter.Tests.dll
 
 workflows:
   version: 2
   build-and-test:
     jobs:
       - build
       - test:
          requires:
           - build