version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run:
          name: build
          command: dotnet build --nologo -c Release
      - run: 
          name: test
          command: dotnet test -c Release
      - run: 
          name: publish
          command: dotnet publish -c Release -o publish
      - persist_to_workspace:
          root: .\publish
        
  publish:
    docker:
      - image: 'cibuilds/github:0.10'
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: compress
          command: >
            $ProgressPreference = "SilentlyContinue"; 
            Compress-Archive -LiteralPath . -DestinationPath ./arbiter.zip
      - run:
          name: push
          command: > 
            VERSION=$(my-binary --version) 
            ghr -t ${GITHUB_TOKEN} 
                -u ${CIRCLE_PROJECT_USERNAME} 
                -r ${CIRCLE_PROJECT_REPONAME} 
                -c ${CIRCLE_SHA1} 
                -delete ${VERSION} 
                ./arbiter.zip
workflows:
  version: 2
  main:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
