 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build --nologo -c Release
       - run: $ProgressPreference = "SilentlyContinue"; Compress-Archive -LiteralPath .\src\Arbiter\bin\Release\net48 -DestinationPath .\arbiter.zip
       - persist_to_workspace:
          root: .
          paths: 
            - .\src\Arbiter.Tests\bin\Release\net48
            - .\arbiter.zip

   test:
     executor: win/default

     steps:
        - attach_workspace:
            at: .\workspace
        - run: dotnet test
        - store_test_results:
           path: TestResult.xml

   publish-github-release:
     docker:
       - image: cibuilds/github:0.10
     steps:
       - attach_workspace:
           at: ./workspace
       - run:
           name: "Publish Release on GitHub"
           command: |
             VERSION=$(my-binary --version)
             ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./workspace/arbiter.zip
 
 workflows:
   version: 2

   main:
     jobs:
      - build
      - test:
          requires:
           - build
      - publish-github-release:
          requires:
          - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/      